### ISSUE TITLE
Update citeproc-php

### ISSUE THREAD

**Issue by thebodzio** [OleVik/grav-plugin-bibliography#3]
Using the latest Grav (1.7.38) with this plugin throws an error “Array and string offset access syntax with curly braces is no longer supported”. It is caused by the file `user/plugins/bibliography/vendor/seboettg/citeproc-php/src/Seboettg/CiteProc/Styles/AffixesTrait.php`. AFAIK there's newer version of https://github.com/seboettg/citeproc-php available, so there's a big chance that updating the code in your plugin should fix the problem.

**Comment by OleVik** [comment]
This is an incompatibility with PHP, wherein [curly braces were deprecated](https://wiki.php.net/rfc/deprecate_curly_braces_array_access), and Citeproc created a fix in [v2.2.0](https://github.com/seboettg/citeproc-php/commit/63dc26c8093dcad90d3f4129c38caa6b23f0508e). I'll look at integrating the updated version.

**Comment by OleVik** [comment]
This should be fixed in [v3.0.0](https://github.com/OleVik/grav-plugin-bibliography/releases/tag/v.3.0.0).
